/**
 * Local storage store name, this is prefixed to all async store keys.
 * @var string
 */
export const STORE_NAME = '@URI';

/**
 * List of available async store keys
 */
export const STORE_KEYS = {
  AUTHENTICATED: STORE_NAME + '@AUTHENTICATED',
  THEME: STORE_NAME + '@THEME',
  TEMP_EMAIL: STORE_NAME + '@TEMP_EMAIL',
  USER_DETAILS: STORE_NAME + '@USER_DETAILS',
  USER_PROFILE: STORE_NAME + '@USER_PROFILE',
  USER_TOKENS: STORE_NAME + '@USER_TOKENS',
  TEMP_USER_TYPE: STORE_NAME + '@USER_TYPE',
  TEMP_INFLUENCER_ID: STORE_NAME + '@INFLUENCER_ID',
  TEMP_INFLUENCER_NAME: STORE_NAME + '@INFLUENCER_NAME',
  TEMP_CONNECT_ACCOUNT_NAME: STORE_NAME + '@CONNECT_ACCOUNT_NAME',
  REMEMBER_ME_EMAIL_KEY: STORE_NAME + '@REMEMBER_ME_EMAIL',
  REMEMBER_ME_PASSWORD_KEY: STORE_NAME + '@REMEMBER_ME_PASSWORD',
  LAST_FEEDBACK_MODAL_DATE: STORE_NAME + '@LAST_FEEDBACK_MODAL_DATE',
  USER_SUBSCRIPTION_PLAN_TYPE: STORE_NAME + '@USER_SUBSCRIPTION_PLAN_TYPE',
};
