export enum AccountDeletionReasonEnum {
  PRIVACY_CONCERNS = 'PRIVACY CONCERNS',
  PREFERRED_ALTERNATIVE = 'PREFERRED ALTERNATIVE',
  ACCOUNT_CONPROMISED = 'ACCOUNT COMPROMISED',
  OTHER = 'OTHER',
}
