export enum AgreementTypeEnum {
  CHAT_USAGE = "CHAT_USAGE",
  APP_USAGE = "APP_USAGE",
  PRIVACY_POLICY = "PRIVACY_POLICY",
  TERMS_OF_SERVICE = "TERMS_OF_SERVICE",
  INSTAGRAM_ACCESS_TOKEN = "INSTAGRAM_ACCESS_TOKEN",
  FACEBOOK = "FACEBOOK_ACCESS_TOKEN",
  TIKTOK = "TIKTOK_ACCESS_TOKEN",
  OTHER = "OTHER",
  X = "X_ACCESS_TOKEN",
  LINKEDIN = "LINKEDIN_ACCESS_TOKEN",
}
