export enum CreativeCategoriesEnum {
  MODEL = 'MODEL',
  PRINTER = 'PRINTER',
  VENDOR = 'VENDOR',
  STYLIST = 'STYLIST',
  PHOTOGRAPHER = 'PHOTOGRAPGER',
  USHER = 'USHER',
  ACTOR = 'ACTOR',
  PHOTOGRAPGER = 'PHOTOGRAPGER',
  DANCER = 'DANCER',
  CONTENT_CREATOR = 'CONTENT_CREATOR',
  BRAND_AMBASSADOR = 'BRAND_AMBASSADOR',
}
