export enum CampaignPlatformEnum {
  INSTAGRAM = 'INSTAGRAM',
  FACEBOOK = 'FACEBOOK',
  TIKTOK = 'TIKTOK',
  X = 'X',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  REDDIT = 'REDDIT',
  SNAPCHAT = 'SNAPCHAT',
  WHATSAPP = 'WHATSAPP',
  TELEGRAM = 'TELEGRAM',
  DISCORD = 'DISCORD',
  NAIRALAND = 'NAIRALAND',
  WEBSITE = 'WEBSITE',
  // Job Boards
  JOBBERMAN = 'JOBBERMAN',
  LINKEDIN_JOBS = 'LINKEDIN_JOBS',
  INDEED = 'INDEED',
}
