export enum TokenProviderEnum {
  FACEBOOK = "FACEBOOK",
  TIKTOK = "TIKTOK",
  TWITTER = "TWITTER",
  LINKEDIN = "LINKEDIN",
  INSTAGRAM = "INSTAGRAM",
}

export enum TokenUsageTypeEnum {
  FACEBOOK_ACCESS_TOKEN = "FACEBOOK_ACCESS_TOKEN",
  TIKTOK_ACCESS_TOKEN = "TIKTOK_ACCESS_TOKEN",
  TWITTER_USER_ACCESS_TOKEN = "TWITTER_USER_ACCESS_TOKEN",
  LINKEDIN_ACCESS_TOKEN = "LINKEDIN_USER_ACCESS_TOKEN",
  INSTAGRAM_ACCESS_TOKEN = "INSTAGRAM_ACCESS_TOKEN",
}
