name: Deploy Next.js to Azure

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          npm run build

      - name: Zip artifact
        run: zip -r app.zip .next package.json package-lock.json node_modules public

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE4B58B545D141BAAF5C3457DD332B58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8C1A038B9CF64D6C8B3255718E1540A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0E275EF339394B79AB6D79F3F5F0AD24 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uri-frontend-2'
          slot-name: 'Production'
          package: app.zip
